In [7]:
import pandas as pd
import numpy as np
import datetime
import os

now = datetime.datetime.now()
organism = 'rice'
directory = f'../Data/07_extract_gene/HN5_genelist_{organism}_{now.strftime("%y%m")}'
os.makedirs(directory, exist_ok=True)

# RICE

In [8]:
HNscore = pd.read_csv(
    "../Data/06_HNscore/HN-score_rice_250524/HN-score_rice_250524_HN5_all.tsv", 
    sep='\t'
)
display(HNscore)

             GENEID  UP5  DOWN5  UNCHANGED5  HN5  UPcount+1 / DOWNcount+1 5
0      Os04g0107900  263      8          89  255                  29.333333
1      Os01g0136100  253      8          99  245                  28.222222
2      Os02g0259900  246      8         106  238                  27.444444
3      Os02g0259850  245      8         107  237                  27.333333
4      Os03g0245800  248     11         101  237                  20.750000
...             ...  ...    ...         ...  ...                        ...
35686  Os01g0952800    7    180         173 -173                   0.044199
35687  Os07g0142100   11    187         162 -176                   0.063830
35688  Os03g0307200    4    184         172 -180                   0.027027
35689  Os07g0142200    9    195         156 -186                   0.051020
35690  Os03g0307300    5    209         146 -204                   0.028571

[35691 rows x 6 columns]

In [9]:
# Calculate the number of genes in the top 1% and bottom 1%
top_1_percent_count = int(len(HNscore) * 0.01)
bottom_1_percent_count = top_1_percent_count

# retrieve the threshold values for the top 1% and bottom 1%
top_1_percent_threshold = HNscore["HN5"].nlargest(top_1_percent_count).min()
bottom_1_percent_threshold = HNscore["HN5"].nsmallest(bottom_1_percent_count).max()

# retrieve the top 1% of the data (including additional rows with the same HN-score)
top_genes = HNscore[HNscore["HN5"] >= top_1_percent_threshold]
# retrieve the bottom 1% of the data (including additional rows with the same HN-score)
bottom_genes = HNscore[HNscore["HN5"] <= bottom_1_percent_threshold]

# print the results
print(f"Top 1% threshold: {top_1_percent_threshold}")
print(f"Bottom 1% threshold: {bottom_1_percent_threshold}")
print(f"Number of genes in the top 1%: {len(top_genes)}")
print(f"Number of genes in the bottom 1%: {len(bottom_genes)}")

# save the results to a file
top_genes.to_csv(f'{directory}/HN5_genes_up_{organism}.tsv', sep='\t', index=False)
bottom_genes.to_csv(f'{directory}/HN5_genes_down_{organism}.tsv', sep='\t', index=False)

Top 1% threshold: 42
Bottom 1% threshold: -40
Number of genes in the top 1%: 367
Number of genes in the bottom 1%: 370

In [11]:
rap_db_gene_info = pd.read_csv(
    "../Data/07_RAP-DB_gene_info/IRGSP-1.0_representative_annotation_2025-03-19.tsv",
    sep="\t",
).rename(
    {
        "Locus_ID": "GENEID"
    },
    axis="columns"
)

display(rap_db_gene_info)

,Transcript_ID,GENEID,Description,RAP-DB Gene Symbol Synonym(s),RAP-DB Gene Name Synonym(s),CGSNL Gene Symbol,CGSNL Gene Name,Oryzabase Gene Symbol Synonym(s),Oryzabase Gene Name Synonym(s),GO,InterPro,Transcript evidence,ORF evidence,Curation Date,Literature PMID,Oryzabase Trait Gene ID,Subcellular location,Comment,B5toI1
0,Os01t0100100-01,Os01g0100100,RabGAP/TBC domain containing protein.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Rab-GAP-TBC domain (IPR000195), Rab-GAP-TBC do...",AK242339,Q655M0 (UniProt),NaN,NaN,NaN,NaN,NaN,NaN
1,Os01t0100200-01,Os01g0100200,Conserved hypothetical protein.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AK059894,B8ACR2 (UniProt),NaN,NaN,NaN,NaN,NaN,NaN
2,Os01t0100300-00,Os01g0100300,Cytochrome P450 domain containing protein.,NaN,NaN,NaN,NaN,NaN,NaN,"Molecular Function: heme binding (GO:0020037),...","Cytochrome P450 (IPR001128), Cytochrome P450 s...",AK365211,B9EYQ3 (UniProt),NaN,NaN,NaN,NaN,NaN,"Exon-intron structures, exon and CDS sequences..."
3,Os01t0100400-01,Os01g0100400,Similar to Pectinesterase-like protein.,NaN,NaN,NaN,NaN,NaN,NaN,Molecular Function: copper ion binding (GO:000...,"Multicopper oxidase, second cupredoxin domain ...",AK101455,Q1EPX7 (UniProt),NaN,NaN,NaN,NaN,NaN,NaN
4,Os01t0100466-00,Os01g0100466,Hypothetical protein.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,tplb0021n10 (Wheat FLcDNA),longestORF,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45159,Os12t0641400-02,Os12g0641400,"Sucrose transporter, Tonoplast proton-sucrose ...","OsSUT2, SUT2","SUCROSE TRANSPORTER 2, sucrose transporter 2",SUT2,SUCROSE TRANSPORTER 2,"OsSUT2(t), SUT2M, OsSUT2, OsSUT2M, OsSUT5","sucrose transporter2(t), Sucrose transport pro...",Biological Process: sucrose transport (GO:0015...,"Sucrose/H+ symporter, plant (IPR005989), Major...","AB091672, HQ540307 (Dongjin)",Q0ILJ3,"May 31, 2017",21771914,2208,tonoplast (GO:0009705),NaN,NaN
45160,Os12t0641500-01,Os12g0641500,Similar to SMC1 protein.,NaN,NaN,SMC1,STRUCTURAL MAINTENANCE OF CHROMOSOMES PROTEIN 1,OsSMC1,structural maintenance of chromosomes protein 6,Biological Process: chromosome organization (G...,"RecF/RecN/SMC, N-terminal (IPR003395), SMCs fl...",AK120333,Q8GU56 (UniProt),NaN,NaN,25936,NaN,NaN,NaN
45161,Os12t0641500-02,Os12g0641500,Similar to SMC1 protein.,NaN,NaN,SMC1,STRUCTURAL MAINTENANCE OF CHROMOSOMES PROTEIN 1,OsSMC1,structural maintenance of chromosomes protein 6,Biological Process: chromosome organization (G...,"RecF/RecN/SMC, N-terminal (IPR003395), SMCs fl...",AK242597,Q8GU56 (UniProt),NaN,NaN,25936,NaN,NaN,NaN
45162,Os12t0641500-03,Os12g0641500,Similar to RecF/RecN/SMC N terminal domain con...,NaN,NaN,SMC1,STRUCTURAL MAINTENANCE OF CHROMOSOMES PROTEIN 1,OsSMC1,structural maintenance of chromosomes protein 6,Biological Process: chromosome organization (G...,"RecF/RecN/SMC, N-terminal (IPR003395), SMCs fl...",AK065733,Q2QLI0 (UniProt),NaN,NaN,25936,NaN,NaN,NaN
45163,Os12t0641600-01,Os12g0641600,Non-protein coding transcript.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AK289049,NONE,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
display(top_genes)
display(bottom_genes)

           GENEID  UP5  DOWN5  UNCHANGED5  HN5  UPcount+1 / DOWNcount+1 5
0    Os04g0107900  263      8          89  255                  29.333333
1    Os01g0136100  253      8          99  245                  28.222222
2    Os02g0259900  246      8         106  238                  27.444444
3    Os02g0259850  245      8         107  237                  27.333333
4    Os03g0245800  248     11         101  237                  20.750000
..            ...  ...    ...         ...  ...                        ...
362  Os05g0550300   57     15         288   42                   3.625000
363  Os06g0651200   64     22         274   42                   2.826087
364  Os08g0374600   93     51         216   42                   1.807692
365  Os10g0440500   55     13         292   42                   4.000000
366  Os12g0111700   57     15         288   42                   3.625000

[367 rows x 6 columns]

             GENEID  UP5  DOWN5  UNCHANGED5  HN5  UPcount+1 / DOWNcount+1 5
35321  Os01g0192900   12     52         296  -40                   0.245283
35322  Os01g0248701   22     62         276  -40                   0.365079
35323  Os01g0813800   15     55         290  -40                   0.285714
35324  Os01g0940700   16     56         288  -40                   0.298246
35325  Os01g0949900   11     51         298  -40                   0.230769
...             ...  ...    ...         ...  ...                        ...
35686  Os01g0952800    7    180         173 -173                   0.044199
35687  Os07g0142100   11    187         162 -176                   0.063830
35688  Os03g0307200    4    184         172 -180                   0.027027
35689  Os07g0142200    9    195         156 -186                   0.051020
35690  Os03g0307300    5    209         146 -204                   0.028571

[370 rows x 6 columns]

In [17]:
# top_genesとrap_db_gene_infoを'GENEID'をキーにして結合します
# 'how="left"'はtop_genesのすべての行を保持し、rap_db_gene_infoから一致する情報を追加します
top_genes_with_info = pd.merge(top_genes, rap_db_gene_info, on='GENEID', how='left')

top_genes_with_info.to_csv(f'{directory}/HN5_genes_up_{organism}_with_info.tsv', sep='\t', index=False)

# 結合後のデータフレームを表示
display(top_genes_with_info)

,GENEID,UP5,DOWN5,UNCHANGED5,HN5,UPcount+1 / DOWNcount+1 5,Transcript_ID,Description,RAP-DB Gene Symbol Synonym(s),RAP-DB Gene Name Synonym(s),...,GO,InterPro,Transcript evidence,ORF evidence,Curation Date,Literature PMID,Oryzabase Trait Gene ID,Subcellular location,Comment,B5toI1
0,Os04g0107900,263,8,89,255,29.333333,Os04t0107900-01,Similar to Heat shock protein 82.,NaN,NaN,...,Biological Process: protein folding (GO:000645...,"Heat shock protein Hsp90 family (IPR001404), H...",AK063698,NP_001135416.2 (RefSeq),NaN,NaN,15517,NaN,NaN,NaN
1,Os04g0107900,263,8,89,255,29.333333,Os04t0107900-02,Heat shock protein 81-1 (HSP81-1) (Heat shock ...,NaN,NaN,...,Biological Process: protein folding (GO:000645...,"Heat shock protein Hsp90 family (IPR001404), H...",AK063568,NP_200076.1 (RefSeq),NaN,NaN,15517,NaN,NaN,NaN
2,Os04g0107900,263,8,89,255,29.333333,Os04t0107900-03,Similar to Heat shock protein 80.,NaN,NaN,...,Biological Process: protein folding (GO:000645...,"Heat shock protein Hsp90 family (IPR001404), H...",AK063751,NP_200414.1 (RefSeq),NaN,NaN,15517,NaN,NaN,NaN
3,Os04g0107900,263,8,89,255,29.333333,Os04t0107900-04,Similar to Heat shock protein 82.,NaN,NaN,...,Biological Process: protein folding (GO:000645...,"Heat shock protein Hsp90 family (IPR001404), H...",AK063629,NP_001135416.2 (RefSeq),NaN,NaN,15517,NaN,NaN,NaN
4,Os04g0107900,263,8,89,255,29.333333,Os04t0107900-05,Non-protein coding transcript.,NaN,NaN,...,NaN,NaN,AK105370,NONE,NaN,NaN,15517,NaN,NaN,CDS sequences are different between Build 5 an...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
435,Os05g0550300,57,15,288,42,3.625000,Os05t0550300-01,Similar to Lipid transfer protein (Fragment).,NaN,NaN,...,Biological Process: lipid transport (GO:0006869),Bifunctional inhibitor/plant lipid transfer pr...,AK062463,P93191 (UniProt),NaN,NaN,13532,NaN,NaN,NaN
436,Os06g0651200,64,22,274,42,2.826087,Os06t0651200-01,Conserved hypothetical protein.,NaN,NaN,...,NaN,NaN,AK107748,A2YFP3 (UniProt),NaN,NaN,NaN,NaN,NaN,NaN
437,Os08g0374600,93,51,216,42,1.807692,Os08t0374600-00,Similar to Receptor kinase-like protein.,NaN,NaN,...,Biological Process: protein phosphorylation (G...,"Protein kinase domain (IPR000719), Serine-thre...",ab initio prediction,Q84PD4 (UniProt),NaN,NaN,18943,NaN,NaN,"Exon-intron structures, exon and CDS sequences..."
438,Os10g0440500,55,13,292,42,4.000000,Os10t0440500-00,Heavy metal transport/detoxification protein d...,NaN,NaN,...,Molecular Function: metal ion binding (GO:0046...,"Heavy metal-associated domain, HMA (IPR006121)...",AY224486,GeneMark,NaN,NaN,23558,NaN,NaN,NaN
439,Os12g0111700,57,15,288,42,3.625000,Os12t0111700-00,Conserved hypothetical protein.,NaN,NaN,...,NaN,NaN,AK363915,B9GBH8 (UniProt),NaN,NaN,20464,NaN,NaN,"Exon-intron structures, exon and CDS sequences..."

In [19]:
bottom_genes_with_info = pd.merge(bottom_genes, rap_db_gene_info, on='GENEID', how='left')

bottom_genes_with_info.to_csv(f'{directory}/HN5_genes_down_{organism}_with_info.tsv', sep='\t', index=False)

display(bottom_genes_with_info)

,GENEID,UP5,DOWN5,UNCHANGED5,HN5,UPcount+1 / DOWNcount+1 5,Transcript_ID,Description,RAP-DB Gene Symbol Synonym(s),RAP-DB Gene Name Synonym(s),...,GO,InterPro,Transcript evidence,ORF evidence,Curation Date,Literature PMID,Oryzabase Trait Gene ID,Subcellular location,Comment,B5toI1
0,Os01g0192900,12,52,296,-40,0.245283,Os01t0192900-01,1-aminocyclopropane-1-carboxylic acid synthase...,OS-ACS5,1-aminocyclopropane-1-carboxylic acid synthase 5,...,Biological Process: biosynthetic process (GO:0...,"Aminotransferases, class-I, pyridoxal-phosphat...","X97066 (IR36), BT068927 (maize)","O24220, Q9FU17","October 15, 2021",12011339,6852,NaN,NaN,NaN
1,Os01g0248701,22,62,276,-40,0.365079,Os01t0248701-01,Geranyl diphosphate (GPP) synthase,OsGPPS,GPP synthase,...,Biological Process: isoprenoid biosynthetic pr...,"Polyprenyl synthetase-like (IPR000092), Isopre...",Inferred from literature,C7IXE8,"July 27, 2021",28607067,23862,chloroplast (GO:0009507),NaN,NaN
2,Os01g0813800,15,55,290,-40,0.285714,Os01t0813800-01,Similar to Beta-glucosidase 3.,NaN,NaN,...,Biological Process: carbohydrate metabolic pro...,"Glycoside hydrolase family 1 (IPR001360), Glyc...",AK067934,Q8RZL1 (UniProt),NaN,NaN,12077,NaN,NaN,CDS sequences are different between Build 5 an...
3,Os01g0813800,15,55,290,-40,0.285714,Os01t0813800-02,"Similar to cDNA, clone: J065127F19, full inser...",NaN,NaN,...,Biological Process: carbohydrate metabolic pro...,"Glycoside hydrolase family 1 (IPR001360), Glyc...",AK063065,Q8RZL1 (UniProt),NaN,NaN,12077,NaN,NaN,NaN
4,Os01g0940700,16,56,288,-40,0.298246,Os01t0940700-01,"Similar to Glucan endo-1, 3-beta-glucosidase G...",NaN,NaN,...,Biological Process: carbohydrate metabolic pro...,"Glycoside hydrolase family 17 (IPR000490), Gly...",AK060802,GeneMark,NaN,NaN,12545,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427,Os01g0952800,7,180,173,-173,0.044199,Os01t0952800-02,Conserved hypothetical protein.,NaN,NaN,...,NaN,NaN,AK108392,Q5JKZ7 (UniProt),NaN,NaN,9483,NaN,NaN,Exon and CDS sequences are different between B...
428,Os07g0142100,11,187,162,-176,0.063830,Os07t0142100-01,"Iron deficiency-inducible peptide, IMA/FEP pep...",OsIMA2,IRON MAN 2,...,NaN,NaN,"CT836140 (indica), Inferred from literature",Inferred from literature,"November 24, 2020",33206982,23839,NaN,NaN,NaN
429,Os03g0307200,4,184,172,-180,0.027027,Os03t0307200-01,"Nicotianamine synthase 2, Nicotianamine biosyn...","NAS2, OsNAS2","NICOTIANAMINE SYNTHASE 2, rice nicotianamine s...",...,Biological Process: nicotianamine biosynthetic...,"Nicotianamine synthase (IPR004298), S-adenosyl...",AK112011,Q10M19,"January 24, 2014",24251791,3032,NaN,NaN,Exon and CDS sequences are different between B...
430,Os07g0142200,9,195,156,-186,0.051020,Os07t0142200-01,Conserved hypothetical protein.,NaN,NaN,...,NaN,Protein PELPK1/2 (IPR044659),AK108897,A3BGH3 (UniProt),NaN,NaN,10205,NaN,NaN,NaN
431,Os03g0307300,5,209,146,-204,0.028571,Os03t0307300-01,Nicotianamine synthase 1 (EC 2.5.1.43) (S-aden...,NaN,NaN,...,Biological Process: nicotianamine biosynthetic...,"Nicotianamine synthase (IPR004298), S-adenosyl...",AK112069,Q0DSH9 (UniProt),NaN,NaN,3031,NaN,NaN,NaN