# Additional Analysis (2025-12-08)

- The AlphaFold Database (AFDB) has been updated from version 4 to version 6.
- Accordingly, we are adding new representative examples to Table 1, excluding entries already removed from the AFDB.

In [1]:
import polars as pl

&nbsp;

&nbsp;

&nbsp;

## rice upregulated gene group "unique LS-HS" hit pair analysis

In [2]:
rice_up_unique_ls_hs_hit_pair = pl.read_csv(
    "../Data/20_foldseek_result_validate_rice_up/rice_up/250831/foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter4_250831.tsv",
    separator="\t"
)

display(rice_up_unique_ls_hs_hit_pair)

shape: (179, 54)
┌─────────────┬─────────────┬─────┬─────────────┬───┬──────┬─────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5 ┆ UniProt     ┆ … ┆ type ┆ enriched_go ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ --- ┆ Accession   ┆   ┆ ---  ┆ _terms      ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64 ┆ ---         ┆   ┆ str  ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆ str         ┆   ┆      ┆ str         ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪═════╪═════════════╪═══╪══════╪═════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os04g044510 ┆ 235 ┆ Q7XUW5      ┆ … ┆ null ┆ GO:0006457, ┆ true       ┆ true       │
│ t-6871      ┆ 0           ┆     ┆             ┆   ┆      ┆ GO:0009266, ┆            ┆            │
│             ┆             ┆     ┆             ┆   ┆      ┆ GO:000…     ┆            ┆            │
│ foldseek-hi ┆ Os04g044510 ┆ 235 ┆ Q7XUW5      ┆ … ┆ null ┆ GO:0006457, ┆ true       ┆ true       │
│ t-6871      ┆ 0           ┆     ┆             ┆   ┆      ┆ GO:0009266, ┆            ┆            │
│             ┆             ┆     ┆             ┆   ┆      ┆ GO:000…     ┆            ┆            │
│ foldseek-hi ┆ Os01g013600 ┆ 234 ┆ E5D3J8      ┆ … ┆ null ┆ GO:0006457, ┆ true       ┆ false      │
│ t-101       ┆ 0           ┆     ┆             ┆   ┆      ┆ GO:0009266, ┆            ┆            │
│             ┆             ┆     ┆             ┆   ┆      ┆ GO:000…     ┆            ┆            │
│ foldseek-hi ┆ Os01g013600 ┆ 234 ┆ Q943E7      ┆ … ┆ null ┆ GO:0006457, ┆ true       ┆ false      │
│ t-90        ┆ 0           ┆     ┆             ┆   ┆      ┆ GO:0009266, ┆            ┆            │
│             ┆             ┆     ┆             ┆   ┆      ┆ GO:000…     ┆            ┆            │
│ foldseek-hi ┆ Os01g013600 ┆ 234 ┆ Q943E7      ┆ … ┆ null ┆ GO:0006457, ┆ true       ┆ false      │
│ t-129       ┆ 0           ┆     ┆             ┆   ┆      ┆ GO:0009266, ┆            ┆            │
│             ┆             ┆     ┆             ┆   ┆      ┆ GO:000…     ┆            ┆            │
│ …           ┆ …           ┆ …   ┆ …           ┆ … ┆ …    ┆ …           ┆ …          ┆ …          │
│ foldseek-hi ┆ Os10g053230 ┆ 44  ┆ Q8LN41      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-13427     ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os04g055820 ┆ 43  ┆ A0A0P0WDA2  ┆ … ┆ null ┆ GO:0005737  ┆ true       ┆ false      │
│ t-7212      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os04g055820 ┆ 43  ┆ A0A0P0WDA2  ┆ … ┆ null ┆ GO:0005737  ┆ true       ┆ false      │
│ t-7212      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os04g055820 ┆ 43  ┆ A0A0P0WDA2  ┆ … ┆ null ┆ GO:0005737  ┆ true       ┆ false      │
│ t-7212      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os04g055820 ┆ 43  ┆ A0A0P0WDA2  ┆ … ┆ null ┆ GO:0005737  ┆ true       ┆ false      │
│ t-7212      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴─────────────┴───┴──────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

## InterPro ID & Ensembl pan-homology info & no enrichment result

In [11]:
rice_up_unique_ls_hs_hit_pair_ip_ensembl = rice_up_unique_ls_hs_hit_pair.filter(
    (pl.col("enrichment_result") == False) & # This is not encluded in the enrichment analysis
    (pl.col("type").is_not_null()) # This mentions that the Ensembl pan-homology information is available
)

# candidate hit pair 1 Os03g0830500 (HN-score: 61)
Os03g0830500 = rice_up_unique_ls_hs_hit_pair.filter(
    (pl.col("From") == "Os03g0830500")
)

# candidate hit pair 2 Os08g0442200 (HN-score: 48) ← keep this pair
Os08g0442200 = rice_up_unique_ls_hs_hit_pair.filter(
    (pl.col("From") == "Os08g0442200")
)

display(Os03g0830500)
display(Os08g0442200)
display(rice_up_unique_ls_hs_hit_pair_ip_ensembl)

shape: (2, 54)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ type       ┆ enriched_g ┆ enrichmen ┆ foldseek_ │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ ---        ┆ o_terms    ┆ t_result  ┆ tm_method │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ str        ┆ ---        ┆ ---       ┆ ---       │
│            ┆            ┆     ┆ str        ┆   ┆            ┆ str        ┆ bool      ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os03g08305 ┆ 61  ┆ Q850Y9     ┆ … ┆ null       ┆            ┆ false     ┆ false     │
│ it-6283    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os03g08305 ┆ 61  ┆ Q850Y9     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-6283    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

shape: (1, 54)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ type       ┆ enriched_g ┆ enrichmen ┆ foldseek_ │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ ---        ┆ o_terms    ┆ t_result  ┆ tm_method │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ str        ┆ ---        ┆ ---       ┆ ---       │
│            ┆            ┆     ┆ str        ┆   ┆            ┆ str        ┆ bool      ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os08g04422 ┆ 48  ┆ A0A0P0XGD7 ┆ … ┆ ortholog_o ┆            ┆ false     ┆ false     │
│ it-12180   ┆ 00         ┆     ┆            ┆   ┆ ne2many    ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

shape: (8, 54)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ type       ┆ enriched_g ┆ enrichmen ┆ foldseek_ │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ ---        ┆ o_terms    ┆ t_result  ┆ tm_method │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ str        ┆ ---        ┆ ---       ┆ ---       │
│            ┆            ┆     ┆ str        ┆   ┆            ┆ str        ┆ bool      ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os03g08305 ┆ 61  ┆ Q850Y9     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-6283    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os05g02005 ┆ 57  ┆ B7EKD2     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7850    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os05g02005 ┆ 57  ┆ B7EKD2     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7852    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os05g02005 ┆ 57  ┆ B7EKD2     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7854    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os05g02005 ┆ 57  ┆ B7EKD2     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7921    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os05g02005 ┆ 57  ┆ B7EKD2     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7935    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os08g04422 ┆ 48  ┆ A0A0P0XGD7 ┆ … ┆ ortholog_o ┆            ┆ false     ┆ false     │
│ it-12180   ┆ 00         ┆     ┆            ┆   ┆ ne2many    ┆            ┆           ┆           │
│ foldseek-h ┆ Os02g05131 ┆ 46  ┆ Q6K602     ┆ … ┆ ortholog_o ┆            ┆ false     ┆ false     │
│ it-2124    ┆ 00         ┆     ┆            ┆   ┆ ne2many    ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

&nbsp;

&nbsp;

## InterPro ID & no enrichment result

### Replace "A0A0P0Y9Z0" to another entry in rice_up_unique_ls_hs_hit_pair

In [15]:
rice_up_unique_ls_hs_hit_pair_replace = rice_up_unique_ls_hs_hit_pair.filter(
    (
        (pl.col("enrichment_result") == False) & # This is not encluded in the enrichment analysis
        (pl.col("InterPro ID intersection tag") == "have common InterPro ID") &
        (pl.col("type").is_null().all().over("From")) # All rows for this "From" gene have null type (no Ensembl pan-homology info at gene level)
    ) & 
    (
        (pl.col("From") != "Os12g0478200") & # pair accession "A0A0P0Y9Z0" (highest average lDDT) is obsolete (2025-12-08)
        (pl.col("From") != "Os01g0860601") & # pair accession "Q5N7C3" (highest average lDDT) is obsolete (2025-12-08)
        (pl.col("From") != "Os02g0711300") & # pair accession "Q0DY72" (highest average lDDT) is obsolete (2025-12-08)
        (pl.col("From") != "Os04g0185600") &  # pair accession "Q7X7V2" (highest average lDDT) is obsolete (2025-12-08)
        (pl.col("From") != "Os02g0649300") &  # human accession "P52954" is obsolete (2025-12-08)
        (pl.col("From") != "Os03g0820300")   # pLDDT is not high overall, so filtering (e.g. E5RH04)
    )
)

# candidate hit pair 1 Os01g0348900 (HN-score: 53)
Os01g0348900 = rice_up_unique_ls_hs_hit_pair.filter(
    (pl.col("From") == "Os01g0348900")
)

# candidate hit pair 2 Os09g0444900 (HN-score: 45) ← keep this pair
Os09g0444900 = rice_up_unique_ls_hs_hit_pair.filter(
    (pl.col("From") == "Os09g0444900")
)

display(Os01g0348900)
display(Os09g0444900)
display(rice_up_unique_ls_hs_hit_pair_replace)

shape: (1, 54)
┌─────────────┬─────────────┬─────┬─────────────┬───┬──────┬─────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5 ┆ UniProt     ┆ … ┆ type ┆ enriched_go ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ --- ┆ Accession   ┆   ┆ ---  ┆ _terms      ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64 ┆ ---         ┆   ┆ str  ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆ str         ┆   ┆      ┆ str         ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪═════╪═════════════╪═══╪══════╪═════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os01g034890 ┆ 53  ┆ Q0JMY8      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-552       ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴─────────────┴───┴──────┴─────────────┴────────────┴────────────┘

shape: (2, 54)
┌─────────────┬─────────────┬─────┬─────────────┬───┬──────┬─────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5 ┆ UniProt     ┆ … ┆ type ┆ enriched_go ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ --- ┆ Accession   ┆   ┆ ---  ┆ _terms      ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64 ┆ ---         ┆   ┆ str  ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆ str         ┆   ┆      ┆ str         ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪═════╪═════════════╪═══╪══════╪═════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os09g044490 ┆ 45  ┆ A0A0P0XNJ7  ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-12582     ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os09g044490 ┆ 45  ┆ A0A0P0XNJ7  ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-12588     ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴─────────────┴───┴──────┴─────────────┴────────────┴────────────┘

shape: (4, 54)
┌─────────────┬─────────────┬─────┬─────────────┬───┬──────┬─────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5 ┆ UniProt     ┆ … ┆ type ┆ enriched_go ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ --- ┆ Accession   ┆   ┆ ---  ┆ _terms      ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64 ┆ ---         ┆   ┆ str  ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆ str         ┆   ┆      ┆ str         ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪═════╪═════════════╪═══╪══════╪═════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os01g034890 ┆ 53  ┆ Q0JMY8      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-552       ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os09g044490 ┆ 45  ┆ A0A0P0XNJ7  ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-12582     ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os09g044490 ┆ 45  ┆ A0A0P0XNJ7  ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-12588     ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os10g053230 ┆ 44  ┆ Q8LN41      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-13427     ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴─────────────┴───┴──────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

## no enrichment result

In [19]:
rice_up_unique_ls_hs_hit_pair_no_enrichment = rice_up_unique_ls_hs_hit_pair.filter(
    (
        (pl.col("enrichment_result") == False) &
        (pl.col("InterPro ID intersection tag") != "have common InterPro ID")
    )
)

# candidate hit pair 1 Os03g0817100 (HN-score: 54) ← keep this pair
Os03g0817100 = rice_up_unique_ls_hs_hit_pair_no_enrichment.filter(
    (pl.col("From") == "Os03g0817100")
).sort(
    by="lddt",
    descending=True
)

display(Os03g0817100)
display(rice_up_unique_ls_hs_hit_pair_no_enrichment)

shape: (9, 54)
┌─────────────┬─────────────┬─────┬─────────────┬───┬──────┬─────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5 ┆ UniProt     ┆ … ┆ type ┆ enriched_go ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ --- ┆ Accession   ┆   ┆ ---  ┆ _terms      ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64 ┆ ---         ┆   ┆ str  ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆ str         ┆   ┆      ┆ str         ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪═════╪═════════════╪═══╪══════╪═════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5849      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5849      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5849      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5849      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5851      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-5848      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-5847      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-5847      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-5847      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴─────────────┴───┴──────┴─────────────┴────────────┴────────────┘

shape: (11, 54)
┌─────────────┬─────────────┬─────┬─────────────┬───┬──────┬─────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5 ┆ UniProt     ┆ … ┆ type ┆ enriched_go ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ --- ┆ Accession   ┆   ┆ ---  ┆ _terms      ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64 ┆ ---         ┆   ┆ str  ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆ str         ┆   ┆      ┆ str         ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪═════╪═════════════╪═══╪══════╪═════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os07g067520 ┆ 92  ┆ C7J4R2      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-11580     ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os07g067520 ┆ 92  ┆ C7J4R2      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-11580     ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-5847      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-5847      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-5847      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ false      │
│ t-5848      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5849      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5849      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5849      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5849      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g081710 ┆ 54  ┆ B9F6Z0      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-5851      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴─────────────┴───┴──────┴─────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## rice downregulated gene group "unique LS-HS" hit pair analysis

In [20]:
rice_down_unique_ls_hs_hit_pair = pl.read_csv(
    "../Data/20_foldseek_result_validate_rice_down/rice_down/250831/foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter4_250831.tsv",
    separator="\t"
)

display(rice_down_unique_ls_hs_hit_pair)

shape: (298, 54)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5  ┆ UniProt    ┆ … ┆ type       ┆ enriched_ ┆ enrichmen ┆ foldseek_ │
│ ---        ┆ ---        ┆ ---  ┆ Accession  ┆   ┆ ---        ┆ go_terms  ┆ t_result  ┆ tm_method │
│ str        ┆ str        ┆ i64  ┆ ---        ┆   ┆ str        ┆ ---       ┆ ---       ┆ ---       │
│            ┆            ┆      ┆ str        ┆   ┆            ┆ str       ┆ bool      ┆ bool      │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os09g05542 ┆ -40  ┆ A0A0P0XRD9 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-10457   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os09g05542 ┆ -40  ┆ A0A0P0XRD9 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-10459   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os09g05542 ┆ -40  ┆ A0A0P0XRD9 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-10461   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os02g05847 ┆ -41  ┆ Q6YY34     ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-3509    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os02g05847 ┆ -41  ┆ Q6YY34     ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-3513    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os02g05847 ┆ -41  ┆ Q6YY34     ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-3513    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os02g05847 ┆ -41  ┆ Q6YY34     ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-3513    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g01791 ┆ -41  ┆ A0A0P0W7F3 ┆ … ┆ null       ┆ GO:001649 ┆ true      ┆ false     │
│ it-5293    ┆ 00         ┆      ┆            ┆   ┆            ┆ 1         ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41  ┆ A0A0P0XIE0 ┆ … ┆ ortholog_m ┆           ┆ false     ┆ true      │
│ it-9313    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆           ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41  ┆ A0A0P0XIE0 ┆ … ┆ ortholog_m ┆           ┆ false     ┆ true      │
│ it-9345    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆           ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41  ┆ A0A0P0XIE0 ┆ … ┆ ortholog_m ┆           ┆ false     ┆ true      │
│ it-9363    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆           ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41  ┆ A0A0P0XIE0 ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-9363    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41  ┆ Q6YSZ8     ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-9211    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41  ┆ Q6YSZ8     ┆ … ┆ ortholog_m ┆           ┆ false     ┆ false     │
│ it-9344    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆           ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41  ┆ Q6YSZ8     ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-9360    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41  ┆ Q6YSZ8     ┆ … ┆ ortholog_m ┆           ┆ false     ┆ false     │
│ it-9360    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆           ┆           ┆           │
│ foldseek-h ┆ Os08g01893 ┆ -42  ┆ Q6YZZ6     ┆ … ┆ null       ┆ GO:000557 ┆ true      ┆ true      │
│ it-8982    ┆ 00         ┆      ┆            ┆   ┆            ┆ 6, GO:004 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 8046      ┆           ┆           │
│ foldseek-h ┆ Os12g06108 ┆ -42  ┆ Q0ILZ7     ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-13466   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os12g06108 ┆ -42  ┆ Q0ILZ7     ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-13466   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os12g06108 ┆ -42  ┆ Q0ILZ7     ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-13466   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os12g06108 ┆ -42  ┆ Q0ILZ7     ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-13466   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os12g06108 ┆ -42  ┆ Q0ILZ7     ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-13467   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g06175 ┆ -43  ┆ A0A0P0W081 ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-4186    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g06175 ┆ -43  ┆ A0A0P0W081 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-4187    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g06175 ┆ -43  ┆ A0A0P0W081 ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-4188    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g06175 ┆ -43  ┆ A0A0P0W081 ┆ … ┆ ortholog_m ┆           ┆ false     ┆ true      │
│ it-4190    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g06175 ┆ -43  ┆ A0A0P0W081 ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-4190    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g06175 ┆ -43  ┆ A0A0P0W081 ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-4190    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g05456 ┆ -43  ┆ A0A0P0WCZ3 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-5870    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g05456 ┆ -43  ┆ A0A0P0WCZ3 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-5870    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4508    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4510    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4510    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ ortholog_m ┆ GO:000687 ┆ true      ┆ false     │
│ it-4515    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4515    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4517    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ ortholog_m ┆ GO:000687 ┆ true      ┆ false     │
│ it-4517    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4519    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4519    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4519    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ ortholog_m ┆ GO:000687 ┆ true      ┆ false     │
│ it-4519    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4519    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4519    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4520    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os03g06673 ┆ -75  ┆ Q6L8G1     ┆ … ┆ null       ┆ GO:000687 ┆ true      ┆ false     │
│ it-4520    ┆ 00         ┆      ┆            ┆   ┆            ┆ 9, GO:000 ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ 6826,     ┆           ┆           │
│            ┆            ┆      ┆            ┆   ┆            ┆ GO:006…   ┆           ┆           │
│ foldseek-h ┆ Os12g05552 ┆ -75  ┆ Q0IMQ1     ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-13314   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os12g05552 ┆ -75  ┆ Q0IMQ1     ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-13330   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g04318 ┆ -99  ┆ A0A0P0VZP7 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-4181    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os06g07184 ┆ -101 ┆ A3BFH0     ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-7477    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os11g01549 ┆ -102 ┆ A0A0N7KSG4 ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-12190   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g06555 ┆ -107 ┆ A0A0P0V637 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-1693    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g06555 ┆ -107 ┆ Q5SN79     ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-1712    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g06555 ┆ -107 ┆ Q5SN79     ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-1712    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g06555 ┆ -107 ┆ Q5SN79     ┆ … ┆ null       ┆           ┆ false     ┆ true      │
│ it-1712    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g03817 ┆ -119 ┆ A0A0N7KIY3 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-5468    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g03817 ┆ -119 ┆ A0A0N7KIY3 ┆ … ┆ null       ┆           ┆ false     ┆ false     │
│ it-5470    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g05786 ┆ -147 ┆ A0A0P0WE87 ┆ … ┆ ortholog_m ┆ GO:001649 ┆ true      ┆ false     │
│ it-5876    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆ 1         ┆           ┆           │
│ foldseek-h ┆ Os04g05786 ┆ -147 ┆ A0A0P0WE87 ┆ … ┆ ortholog_m ┆ GO:001649 ┆ true      ┆ false     │
│ it-5877    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆ 1         ┆           ┆           │
│ foldseek-h ┆ Os04g05786 ┆ -147 ┆ A0A0P0WE87 ┆ … ┆ null       ┆ GO:001649 ┆ true      ┆ false     │
│ it-5877    ┆ 00         ┆      ┆            ┆   ┆            ┆ 1         ┆           ┆           │
│ foldseek-h ┆ Os04g05786 ┆ -147 ┆ A0A0P0WE87 ┆ … ┆ ortholog_m ┆ GO:001649 ┆ true      ┆ false     │
│ it-5878    ┆ 00         ┆      ┆            ┆   ┆ any2many   ┆ 1         ┆           ┆           │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

&nbsp;

&nbsp;

## InterPro ID & Ensembl pan-homology info & no enrichment result

In [25]:
rice_down_unique_ls_hs_hit_pair_ip_ensembl = rice_down_unique_ls_hs_hit_pair.filter(
    (pl.col("enrichment_result") == False) &
    (pl.col("type").is_not_null()) &
    (pl.col("From") != "Os07g0561800") # this gene hit pair is obsolete (2025-12-08)
)

# candidate hit pair 1 Os07g0190000 (HN-score: -64) ← keep this pair
Os07g0190000 = rice_down_unique_ls_hs_hit_pair.filter(
    (pl.col("From") == "Os07g0190000")
).sort(
    by="lddt",
    descending=True
)

display(Os07g0190000)
display(rice_down_unique_ls_hs_hit_pair_ip_ensembl)

shape: (6, 54)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ type       ┆ enriched_g ┆ enrichmen ┆ foldseek_ │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ ---        ┆ o_terms    ┆ t_result  ┆ tm_method │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ str        ┆ ---        ┆ ---       ┆ ---       │
│            ┆            ┆     ┆ str        ┆   ┆            ┆ str        ┆ bool      ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os07g01900 ┆ -64 ┆ Q6YU51     ┆ … ┆ null       ┆            ┆ false     ┆ false     │
│ it-7582    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os07g01900 ┆ -64 ┆ Q6YU51     ┆ … ┆ null       ┆            ┆ false     ┆ false     │
│ it-7582    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os07g01900 ┆ -64 ┆ Q6YU51     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7582    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os07g01900 ┆ -64 ┆ Q6YU51     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7593    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os07g01900 ┆ -64 ┆ Q6YU51     ┆ … ┆ null       ┆            ┆ false     ┆ false     │
│ it-7584    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os07g01900 ┆ -64 ┆ Q6YU51     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7584    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

shape: (9, 54)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ type       ┆ enriched_g ┆ enrichmen ┆ foldseek_ │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ ---        ┆ o_terms    ┆ t_result  ┆ tm_method │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ str        ┆ ---        ┆ ---       ┆ ---       │
│            ┆            ┆     ┆ str        ┆   ┆            ┆ str        ┆ bool      ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os08g05478 ┆ -41 ┆ A0A0P0XIE0 ┆ … ┆ ortholog_m ┆            ┆ false     ┆ true      │
│ it-9313    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41 ┆ A0A0P0XIE0 ┆ … ┆ ortholog_m ┆            ┆ false     ┆ true      │
│ it-9345    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41 ┆ A0A0P0XIE0 ┆ … ┆ ortholog_m ┆            ┆ false     ┆ true      │
│ it-9363    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41 ┆ Q6YSZ8     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-9344    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os08g05478 ┆ -41 ┆ Q6YSZ8     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-9360    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os03g06175 ┆ -43 ┆ A0A0P0W081 ┆ … ┆ ortholog_m ┆            ┆ false     ┆ true      │
│ it-4190    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os07g01900 ┆ -64 ┆ Q6YU51     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7582    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os07g01900 ┆ -64 ┆ Q6YU51     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7584    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
│ foldseek-h ┆ Os07g01900 ┆ -64 ┆ Q6YU51     ┆ … ┆ ortholog_m ┆            ┆ false     ┆ false     │
│ it-7593    ┆ 00         ┆     ┆            ┆   ┆ any2many   ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

&nbsp;

&nbsp;

## InterPro ID & no enrichment result

In [29]:
rice_down_unique_ls_hs_hit_pair_replace = rice_down_unique_ls_hs_hit_pair.filter(
    (
        (pl.col("enrichment_result") == False) & # This is not encluded in the enrichment analysis
        (pl.col("InterPro ID intersection tag") == "have common InterPro ID") &
        (pl.col("type").is_null().all().over("From")) # All rows for this "From" gene have null type (no Ensembl pan-homology info at gene level)
    )
)

# candidate hit pair 1 Os03g0372600 (HN-score: -46) ← keep this pair
Os03g0372600 = rice_down_unique_ls_hs_hit_pair.filter(
    (pl.col("From") == "Os03g0372600")
).sort(
    by="lddt",
    descending=True
)

display(Os03g0372600)
pl.Config.set_tbl_rows(10)
display(rice_down_unique_ls_hs_hit_pair_replace)

shape: (4, 54)
┌─────────────┬─────────────┬─────┬─────────────┬───┬──────┬─────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5 ┆ UniProt     ┆ … ┆ type ┆ enriched_go ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ --- ┆ Accession   ┆   ┆ ---  ┆ _terms      ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64 ┆ ---         ┆   ┆ str  ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆ str         ┆   ┆      ┆ str         ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪═════╪═════════════╪═══╪══════╪═════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os03g037260 ┆ -46 ┆ Q84TS2      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-4057      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g037260 ┆ -46 ┆ Q84TS2      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-4057      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g037260 ┆ -46 ┆ Q84TS2      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-4057      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
│ foldseek-hi ┆ Os03g037260 ┆ -46 ┆ Q84TS2      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-4050      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴─────────────┴───┴──────┴─────────────┴────────────┴────────────┘

shape: (94, 54)
┌─────────────┬─────────────┬──────┬─────────────┬───┬──────┬────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5  ┆ UniProt     ┆ … ┆ type ┆ enriched_g ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ ---  ┆ Accession   ┆   ┆ ---  ┆ o_terms    ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64  ┆ ---         ┆   ┆ str  ┆ ---        ┆ ---        ┆ ---        │
│             ┆             ┆      ┆ str         ┆   ┆      ┆ str        ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪══════╪═════════════╪═══╪══════╪════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os09g055420 ┆ -40  ┆ A0A0P0XRD9  ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-10457     ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os09g055420 ┆ -40  ┆ A0A0P0XRD9  ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-10459     ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os09g055420 ┆ -40  ┆ A0A0P0XRD9  ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-10461     ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os02g058470 ┆ -41  ┆ Q6YY34      ┆ … ┆ null ┆            ┆ false      ┆ true       │
│ t-3509      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os02g058470 ┆ -41  ┆ Q6YY34      ┆ … ┆ null ┆            ┆ false      ┆ true       │
│ t-3513      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ …           ┆ …           ┆ …    ┆ …           ┆ … ┆ …    ┆ …          ┆ …          ┆ …          │
│ foldseek-hi ┆ Os01g065550 ┆ -107 ┆ Q5SN79      ┆ … ┆ null ┆            ┆ false      ┆ true       │
│ t-1712      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os01g065550 ┆ -107 ┆ Q5SN79      ┆ … ┆ null ┆            ┆ false      ┆ true       │
│ t-1712      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os01g065550 ┆ -107 ┆ Q5SN79      ┆ … ┆ null ┆            ┆ false      ┆ true       │
│ t-1712      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os04g038170 ┆ -119 ┆ A0A0N7KIY3  ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-5468      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os04g038170 ┆ -119 ┆ A0A0N7KIY3  ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-5470      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
└─────────────┴─────────────┴──────┴─────────────┴───┴──────┴────────────┴────────────┴────────────┘

&nbsp;

&nbsp;

## no enrichment result

In [34]:
rice_down_unique_ls_hs_hit_pair_no_enrichment = rice_down_unique_ls_hs_hit_pair.filter(
    (
        (pl.col("enrichment_result") == False) &
        (pl.col("InterPro ID intersection tag") != "have common InterPro ID")
    )
)

# candidate hit pair 1 Os07g0524200 (HN-score: -72) ← keep this pair
Os07g0524200 = rice_down_unique_ls_hs_hit_pair_no_enrichment.filter(
    (pl.col("From") == "Os07g0524200")
).sort(
    by="lddt",
    descending=True
)

display(Os07g0524200)

pl.Config.set_tbl_rows(10)
display(rice_down_unique_ls_hs_hit_pair_no_enrichment)

shape: (1, 54)
┌─────────────┬─────────────┬─────┬─────────────┬───┬──────┬─────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5 ┆ UniProt     ┆ … ┆ type ┆ enriched_go ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ --- ┆ Accession   ┆   ┆ ---  ┆ _terms      ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64 ┆ ---         ┆   ┆ str  ┆ ---         ┆ ---        ┆ ---        │
│             ┆             ┆     ┆ str         ┆   ┆      ┆ str         ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪═════╪═════════════╪═══╪══════╪═════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os07g052420 ┆ -72 ┆ Q69SA8      ┆ … ┆ null ┆             ┆ false      ┆ true       │
│ t-8190      ┆ 0           ┆     ┆             ┆   ┆      ┆             ┆            ┆            │
└─────────────┴─────────────┴─────┴─────────────┴───┴──────┴─────────────┴────────────┴────────────┘

shape: (120, 54)
┌─────────────┬─────────────┬──────┬─────────────┬───┬──────┬────────────┬────────────┬────────────┐
│ hit label   ┆ From        ┆ HN5  ┆ UniProt     ┆ … ┆ type ┆ enriched_g ┆ enrichment ┆ foldseek_t │
│ ---         ┆ ---         ┆ ---  ┆ Accession   ┆   ┆ ---  ┆ o_terms    ┆ _result    ┆ m_method   │
│ str         ┆ str         ┆ i64  ┆ ---         ┆   ┆ str  ┆ ---        ┆ ---        ┆ ---        │
│             ┆             ┆      ┆ str         ┆   ┆      ┆ str        ┆ bool       ┆ bool       │
╞═════════════╪═════════════╪══════╪═════════════╪═══╪══════╪════════════╪════════════╪════════════╡
│ foldseek-hi ┆ Os12g061080 ┆ -42  ┆ Q0ILZ7      ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-13466     ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os12g061080 ┆ -42  ┆ Q0ILZ7      ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-13466     ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os12g061080 ┆ -42  ┆ Q0ILZ7      ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-13466     ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os12g061080 ┆ -42  ┆ Q0ILZ7      ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-13466     ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os12g061080 ┆ -42  ┆ Q0ILZ7      ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-13467     ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ …           ┆ …           ┆ …    ┆ …           ┆ … ┆ …    ┆ …          ┆ …          ┆ …          │
│ foldseek-hi ┆ Os04g046860 ┆ -57  ┆ Q7XJV6      ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-5867      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os04g046860 ┆ -57  ┆ Q7XJV6      ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-5867      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os07g052420 ┆ -72  ┆ Q69SA8      ┆ … ┆ null ┆            ┆ false      ┆ true       │
│ t-8190      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os03g043180 ┆ -99  ┆ A0A0P0VZP7  ┆ … ┆ null ┆            ┆ false      ┆ false      │
│ t-4181      ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
│ foldseek-hi ┆ Os11g015490 ┆ -102 ┆ A0A0N7KSG4  ┆ … ┆ null ┆            ┆ false      ┆ true       │
│ t-12190     ┆ 0           ┆      ┆             ┆   ┆      ┆            ┆            ┆            │
└─────────────┴─────────────┴──────┴─────────────┴───┴──────┴────────────┴────────────┴────────────┘