# Additional Analysis (2025-12-13)

- Combine rice-human unique LS-HS hit pair and human HN-score previously reported.
- human HN-score list is available from figshare
- [Table S5: HN-score Data for All Human Genes](https://doi.org/10.6084/m9.figshare.23944935)

In [1]:
import polars as pl

&nbsp;

## human HN-score

In [2]:
# Downloaded from figshare
# https://doi.org/10.6084/m9.figshare.23944935
HNscore_human = pl.read_csv(
    "../Data/24_meta-analysis_human_mouse/HN-score_human_all.csv",
    separator=","
).rename(
    {
        "GeneName": "hgnc_symbol_id",
        "HN5": "human HN-score",
        "up5": "human up5 pair",
        "dn5": "human down5 pair",
        "unchange5": "human unchange5 pair",
        "all": "human all pair"
    }
)

display(HNscore_human)

shape: (19_705, 6)
┌──────────────────┬───────────┬─────────────┬─────────────────┬─────────────────┬─────────────────┐
│ hgnc_symbol_id   ┆ human up5 ┆ human down5 ┆ human unchange5 ┆ human all pair  ┆ human HN-score  │
│ ---              ┆ pair      ┆ pair        ┆ pair            ┆ ---             ┆ ---             │
│ str              ┆ ---       ┆ ---         ┆ ---             ┆ i64             ┆ i64             │
│                  ┆ i64       ┆ i64         ┆ i64             ┆                 ┆                 │
╞══════════════════╪═══════════╪═════════════╪═════════════════╪═════════════════╪═════════════════╡
│ HSPA6            ┆ 247       ┆ 2           ┆ 73              ┆ 322             ┆ 245             │
│ HSPA1A           ┆ 240       ┆ 1           ┆ 81              ┆ 322             ┆ 239             │
│ HSPA1B           ┆ 233       ┆ 2           ┆ 87              ┆ 322             ┆ 231             │
│ DNAJB1           ┆ 212       ┆ 2           ┆ 108             ┆ 322             ┆ 210             │
│ BAG3             ┆ 182       ┆ 1           ┆ 139             ┆ 322             ┆ 181             │
│ …                ┆ …         ┆ …           ┆ …               ┆ …               ┆ …               │
│ N4BP1            ┆ 3         ┆ 44          ┆ 275             ┆ 322             ┆ -41             │
│ ZNF784           ┆ 8         ┆ 50          ┆ 264             ┆ 322             ┆ -42             │
│ TSSK3            ┆ 28        ┆ 71          ┆ 223             ┆ 322             ┆ -43             │
│ HRCT1            ┆ 7         ┆ 59          ┆ 256             ┆ 322             ┆ -52             │
│ H1-3             ┆ 10        ┆ 81          ┆ 231             ┆ 322             ┆ -71             │
└──────────────────┴───────────┴─────────────┴─────────────────┴─────────────────┴─────────────────┘

In [3]:
# In a previous meta-analysis of public gene expression data related to human heat stress, 
# the top 500 genes identified as belonging to the upregulated gene group based on HN-score
# DOI: 10.3390/ijms241713444
HNscore_human_top_500 = HNscore_human.head(500)

top_500_genes = HNscore_human_top_500["hgnc_symbol_id"]

display(HNscore_human_top_500)

shape: (500, 6)
┌──────────────────┬───────────┬─────────────┬─────────────────┬─────────────────┬─────────────────┐
│ hgnc_symbol_id   ┆ human up5 ┆ human down5 ┆ human unchange5 ┆ human all pair  ┆ human HN-score  │
│ ---              ┆ pair      ┆ pair        ┆ pair            ┆ ---             ┆ ---             │
│ str              ┆ ---       ┆ ---         ┆ ---             ┆ i64             ┆ i64             │
│                  ┆ i64       ┆ i64         ┆ i64             ┆                 ┆                 │
╞══════════════════╪═══════════╪═════════════╪═════════════════╪═════════════════╪═════════════════╡
│ HSPA6            ┆ 247       ┆ 2           ┆ 73              ┆ 322             ┆ 245             │
│ HSPA1A           ┆ 240       ┆ 1           ┆ 81              ┆ 322             ┆ 239             │
│ HSPA1B           ┆ 233       ┆ 2           ┆ 87              ┆ 322             ┆ 231             │
│ DNAJB1           ┆ 212       ┆ 2           ┆ 108             ┆ 322             ┆ 210             │
│ BAG3             ┆ 182       ┆ 1           ┆ 139             ┆ 322             ┆ 181             │
│ …                ┆ …         ┆ …           ┆ …               ┆ …               ┆ …               │
│ TEX29            ┆ 45        ┆ 15          ┆ 262             ┆ 322             ┆ 30              │
│ AQP3             ┆ 32        ┆ 2           ┆ 288             ┆ 322             ┆ 30              │
│ FOXD3            ┆ 31        ┆ 1           ┆ 290             ┆ 322             ┆ 30              │
│ TNNC2            ┆ 51        ┆ 21          ┆ 250             ┆ 322             ┆ 30              │
│ LBH              ┆ 38        ┆ 8           ┆ 276             ┆ 322             ┆ 30              │
└──────────────────┴───────────┴─────────────┴─────────────────┴─────────────────┴─────────────────┘

In [4]:
HNscore_human_bottom_500 = HNscore_human.tail(500)

bottom_500_genes = HNscore_human_bottom_500["hgnc_symbol_id"]

display(HNscore_human_bottom_500)

shape: (500, 6)
┌──────────────────┬───────────┬─────────────┬─────────────────┬─────────────────┬─────────────────┐
│ hgnc_symbol_id   ┆ human up5 ┆ human down5 ┆ human unchange5 ┆ human all pair  ┆ human HN-score  │
│ ---              ┆ pair      ┆ pair        ┆ pair            ┆ ---             ┆ ---             │
│ str              ┆ ---       ┆ ---         ┆ ---             ┆ i64             ┆ i64             │
│                  ┆ i64       ┆ i64         ┆ i64             ┆                 ┆                 │
╞══════════════════╪═══════════╪═════════════╪═════════════════╪═════════════════╪═════════════════╡
│ ABCC10           ┆ 7         ┆ 16          ┆ 299             ┆ 322             ┆ -9              │
│ ZNF710           ┆ 8         ┆ 17          ┆ 297             ┆ 322             ┆ -9              │
│ ZNF500           ┆ 4         ┆ 13          ┆ 305             ┆ 322             ┆ -9              │
│ ZNF30            ┆ 7         ┆ 16          ┆ 299             ┆ 322             ┆ -9              │
│ ZNF311           ┆ 0         ┆ 9           ┆ 313             ┆ 322             ┆ -9              │
│ …                ┆ …         ┆ …           ┆ …               ┆ …               ┆ …               │
│ N4BP1            ┆ 3         ┆ 44          ┆ 275             ┆ 322             ┆ -41             │
│ ZNF784           ┆ 8         ┆ 50          ┆ 264             ┆ 322             ┆ -42             │
│ TSSK3            ┆ 28        ┆ 71          ┆ 223             ┆ 322             ┆ -43             │
│ HRCT1            ┆ 7         ┆ 59          ┆ 256             ┆ 322             ┆ -52             │
│ H1-3             ┆ 10        ┆ 81          ┆ 231             ┆ 322             ┆ -71             │
└──────────────────┴───────────┴─────────────┴─────────────────┴─────────────────┴─────────────────┘

&nbsp;

&nbsp;

&nbsp;

## rice upregulated gene group

In [5]:
foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_250831 = pl.read_csv(
    "../Data/20_foldseek_result_validate_rice_up/rice_up/250831/foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_250831.tsv",
    separator="\t"
).join(
    HNscore_human,
    on="hgnc_symbol_id",
    how="left"
).with_columns(
    (pl.col("hgnc_symbol_id").is_in(top_500_genes).alias("is_in_human_top500")),
    (pl.col("hgnc_symbol_id").is_in(bottom_500_genes).alias("is_in_human_bottom500"))
)

foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_250831.write_csv(
    "../Data/20_foldseek_result_validate_rice_up/rice_up/rice_up_supp9_add_human_HNscore/foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_250831_add_human_HNscore.tsv",
    separator="\t"
)

display(foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_250831)

shape: (5_723, 58)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ human all  ┆ human      ┆ is_in_hum ┆ is_in_hum │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ pair       ┆ HN-score   ┆ an_top500 ┆ an_bottom │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ 500       │
│            ┆            ┆     ┆ str        ┆   ┆ i64        ┆ i64        ┆ bool      ┆ ---       │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆           ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os04g01079 ┆ 255 ┆ A0A0P0W604 ┆ … ┆ 322        ┆ 13         ┆ false     ┆ false     │
│ it-6319    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g01079 ┆ 255 ┆ A0A0P0W604 ┆ … ┆ 322        ┆ 13         ┆ false     ┆ false     │
│ it-6320    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g01079 ┆ 255 ┆ A0A0P0W604 ┆ … ┆ 322        ┆ 13         ┆ false     ┆ false     │
│ it-6330    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g01079 ┆ 255 ┆ A0A0P0W604 ┆ … ┆ 322        ┆ 4          ┆ false     ┆ false     │
│ it-6350    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g01079 ┆ 255 ┆ A0A0P0W604 ┆ … ┆ 322        ┆ 68         ┆ true      ┆ false     │
│ it-6352    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ foldseek-h ┆ Os05g04604 ┆ 42  ┆ A0A0P0WN72 ┆ … ┆ 322        ┆ 1          ┆ false     ┆ false     │
│ it-8951    ┆ 75         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os08g03746 ┆ 42  ┆ A0A0P0XF07 ┆ … ┆ 322        ┆ 46         ┆ true      ┆ false     │
│ it-11633   ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os08g03746 ┆ 42  ┆ A0A0P0XF07 ┆ … ┆ 322        ┆ 5          ┆ false     ┆ false     │
│ it-11646   ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os08g03746 ┆ 42  ┆ A0A0P0XF07 ┆ … ┆ 322        ┆ 7          ┆ false     ┆ false     │
│ it-11654   ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os08g03746 ┆ 42  ┆ A0A0P0XF07 ┆ … ┆ 322        ┆ 5          ┆ false     ┆ false     │
│ it-11668   ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [6]:
foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter1_250831 = pl.read_csv(
    "../Data/20_foldseek_result_validate_rice_up/rice_up/250831/foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter1_250831.tsv",
    separator="\t"
).join(
    HNscore_human,
    on="hgnc_symbol_id",
    how="left"
).with_columns(
    (pl.col("hgnc_symbol_id").is_in(top_500_genes).alias("is_in_human_top500")),
    (pl.col("hgnc_symbol_id").is_in(bottom_500_genes).alias("is_in_human_bottom500"))
)

foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter1_250831.write_csv(
    "../Data/20_foldseek_result_validate_rice_up/rice_up/rice_up_supp9_add_human_HNscore/foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter1_250831_add_human_HNscore.tsv",
    separator="\t"
)

display(foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter1_250831)

shape: (1_386, 58)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ human all  ┆ human      ┆ is_in_hum ┆ is_in_hum │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ pair       ┆ HN-score   ┆ an_top500 ┆ an_bottom │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ 500       │
│            ┆            ┆     ┆ str        ┆   ┆ i64        ┆ i64        ┆ bool      ┆ ---       │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆           ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os04g01079 ┆ 255 ┆ A0A0P0W604 ┆ … ┆ 322        ┆ 13         ┆ false     ┆ false     │
│ it-6319    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g01079 ┆ 255 ┆ A0A0P0W604 ┆ … ┆ 322        ┆ 13         ┆ false     ┆ false     │
│ it-6320    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g01079 ┆ 255 ┆ A0A0P0W604 ┆ … ┆ 322        ┆ 13         ┆ false     ┆ false     │
│ it-6330    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g01079 ┆ 255 ┆ A0A0P0W604 ┆ … ┆ 322        ┆ 68         ┆ true      ┆ false     │
│ it-6352    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01361 ┆ 245 ┆ P27777     ┆ … ┆ 322        ┆ 173        ┆ true      ┆ false     │
│ it-198     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ foldseek-h ┆ Os05g04604 ┆ 42  ┆ A0A0P0WN72 ┆ … ┆ 322        ┆ 1          ┆ false     ┆ false     │
│ it-8944    ┆ 75         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os05g04604 ┆ 42  ┆ A0A0P0WN72 ┆ … ┆ 322        ┆ -5         ┆ false     ┆ false     │
│ it-8945    ┆ 75         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os05g04604 ┆ 42  ┆ A0A0P0WN72 ┆ … ┆ 322        ┆ 0          ┆ false     ┆ false     │
│ it-8946    ┆ 75         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os05g04604 ┆ 42  ┆ A0A0P0WN72 ┆ … ┆ 322        ┆ -3         ┆ false     ┆ false     │
│ it-8947    ┆ 75         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os05g04604 ┆ 42  ┆ A0A0P0WN72 ┆ … ┆ 322        ┆ 1          ┆ false     ┆ false     │
│ it-8951    ┆ 75         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [16]:
foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter4_250831 = pl.read_csv(
    "../Data/20_foldseek_result_validate_rice_up/rice_up/250831/foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter4_250831.tsv",
    separator="\t"
).join(
    HNscore_human,
    on="hgnc_symbol_id",
    how="left"
).with_columns(
    (pl.col("hgnc_symbol_id").is_in(top_500_genes).alias("is_in_human_top500")),
    (pl.col("hgnc_symbol_id").is_in(bottom_500_genes).alias("is_in_human_bottom500"))
)

foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter4_250831.write_csv(
    "../Data/20_foldseek_result_validate_rice_up/rice_up/rice_up_supp9_add_human_HNscore/foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter4_250831_add_human_HNscore.tsv",
    separator="\t"
)

print(foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter4_250831.select("hit label").unique())
display(foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter4_250831)

shape: (119, 1)
┌────────────────────┐
│ hit label          │
│ ---                │
│ str                │
╞════════════════════╡
│ foldseek-hit-832   │
│ foldseek-hit-9663  │
│ foldseek-hit-9675  │
│ foldseek-hit-2953  │
│ foldseek-hit-7947  │
│ foldseek-hit-6549  │
│ foldseek-hit-833   │
│ …                  │
│ foldseek-hit-1619  │
│ foldseek-hit-5888  │
│ foldseek-hit-5897  │
│ foldseek-hit-527   │
│ foldseek-hit-9390  │
│ foldseek-hit-13325 │
│ foldseek-hit-14091 │
└────────────────────┘

shape: (179, 61)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ human all  ┆ human      ┆ is_in_hum ┆ is_in_hum │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ pair       ┆ HN-score   ┆ an_top500 ┆ an_bottom │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ 500       │
│            ┆            ┆     ┆ str        ┆   ┆ i64        ┆ i64        ┆ bool      ┆ ---       │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆           ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os04g04451 ┆ 235 ┆ Q7XUW5     ┆ … ┆ 322        ┆ -3         ┆ false     ┆ false     │
│ it-6871    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g04451 ┆ 235 ┆ Q7XUW5     ┆ … ┆ 322        ┆ -3         ┆ false     ┆ false     │
│ it-6871    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01360 ┆ 234 ┆ E5D3J8     ┆ … ┆ 322        ┆ 10         ┆ false     ┆ false     │
│ it-101     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01360 ┆ 234 ┆ Q943E7     ┆ … ┆ 322        ┆ 3          ┆ false     ┆ false     │
│ it-90      ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01360 ┆ 234 ┆ Q943E7     ┆ … ┆ 322        ┆ 73         ┆ true      ┆ false     │
│ it-129     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01362 ┆ 234 ┆ E5D3J7     ┆ … ┆ 322        ┆ 73         ┆ true      ┆ false     │
│ it-288     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01362 ┆ 234 ┆ Q943E6     ┆ … ┆ 322        ┆ 3          ┆ false     ┆ false     │
│ it-251     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ foldseek-h ┆ Os09g04449 ┆ 45  ┆ A0A0P0XNJ7 ┆ … ┆ 322        ┆ 7          ┆ false     ┆ false     │
│ it-12582   ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os09g04449 ┆ 45  ┆ A0A0P0XNJ7 ┆ … ┆ 322        ┆ 7          ┆ false     ┆ false     │
│ it-12588   ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os10g05323 ┆ 44  ┆ Q8LN41     ┆ … ┆ 322        ┆ 6          ┆ false     ┆ false     │
│ it-13427   ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g05582 ┆ 43  ┆ A0A0P0WDA2 ┆ … ┆ 322        ┆ 8          ┆ false     ┆ false     │
│ it-7212    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g05582 ┆ 43  ┆ A0A0P0WDA2 ┆ … ┆ 322        ┆ 8          ┆ false     ┆ false     │
│ it-7212    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g05582 ┆ 43  ┆ A0A0P0WDA2 ┆ … ┆ 322        ┆ 8          ┆ false     ┆ false     │
│ it-7212    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os04g05582 ┆ 43  ┆ A0A0P0WDA2 ┆ … ┆ 322        ┆ 8          ┆ false     ┆ false     │
│ it-7212    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [18]:
rice_up_human_up = foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter4_250831.filter(
    pl.col("is_in_human_top500") == True
)

rice_up_human_up.write_csv(
    "../Data/20_foldseek_result_validate_rice_up/rice_up/rice_up_supp9_add_human_HNscore/foldseek_result_rice_up_domain_panhomology_info_filtercondtion3_filter4_250831_add_human_HNscore_top500.tsv",
    separator="\t"
)

pl.Config.set_tbl_rows(14)
print(rice_up_human_up.select("hit label").unique())
display(rice_up_human_up)

shape: (11, 1)
┌────────────────────┐
│ hit label          │
│ ---                │
│ str                │
╞════════════════════╡
│ foldseek-hit-832   │
│ foldseek-hit-833   │
│ foldseek-hit-129   │
│ foldseek-hit-540   │
│ foldseek-hit-9676  │
│ foldseek-hit-288   │
│ foldseek-hit-9663  │
│ foldseek-hit-9686  │
│ foldseek-hit-13561 │
│ foldseek-hit-17    │
│ foldseek-hit-525   │
└────────────────────┘

shape: (14, 61)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ human all  ┆ human      ┆ is_in_hum ┆ is_in_hum │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ pair       ┆ HN-score   ┆ an_top500 ┆ an_bottom │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ 500       │
│            ┆            ┆     ┆ str        ┆   ┆ i64        ┆ i64        ┆ bool      ┆ ---       │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆           ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os01g01360 ┆ 234 ┆ Q943E7     ┆ … ┆ 322        ┆ 73         ┆ true      ┆ false     │
│ it-129     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01362 ┆ 234 ┆ E5D3J7     ┆ … ┆ 322        ┆ 73         ┆ true      ┆ false     │
│ it-288     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os11g02442 ┆ 223 ┆ Q53M11     ┆ … ┆ 322        ┆ 73         ┆ true      ┆ false     │
│ it-13561   ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01358 ┆ 218 ┆ Q943Q3     ┆ … ┆ 322        ┆ 112        ┆ true      ┆ false     │
│ it-17      ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01841 ┆ 209 ┆ Q5VRY1     ┆ … ┆ 322        ┆ 73         ┆ true      ┆ false     │
│ it-525     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g01841 ┆ 209 ┆ Q5VRY1     ┆ … ┆ 322        ┆ 100        ┆ true      ┆ false     │
│ it-540     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os06g02531 ┆ 120 ┆ Q652V8     ┆ … ┆ 322        ┆ 112        ┆ true      ┆ false     │
│ it-9663    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os06g02531 ┆ 120 ┆ Q652V8     ┆ … ┆ 322        ┆ 79         ┆ true      ┆ false     │
│ it-9676    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os06g02531 ┆ 120 ┆ Q652V8     ┆ … ┆ 322        ┆ 79         ┆ true      ┆ false     │
│ it-9676    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os06g02531 ┆ 120 ┆ Q652V8     ┆ … ┆ 322        ┆ 79         ┆ true      ┆ false     │
│ it-9676    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os06g02531 ┆ 120 ┆ Q652V8     ┆ … ┆ 322        ┆ 79         ┆ true      ┆ false     │
│ it-9676    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os06g02531 ┆ 120 ┆ Q652V8     ┆ … ┆ 322        ┆ 73         ┆ true      ┆ false     │
│ it-9686    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g06069 ┆ 61  ┆ Q5ZBN6     ┆ … ┆ 322        ┆ 34         ┆ true      ┆ false     │
│ it-832     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
│ foldseek-h ┆ Os01g06069 ┆ 61  ┆ Q5ZBN6     ┆ … ┆ 322        ┆ 34         ┆ true      ┆ false     │
│ it-833     ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

&nbsp;

&nbsp;

&nbsp;

&nbsp;

## rice downregulated gene group

In [8]:
foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_250831 = pl.read_csv(
    "../Data/20_foldseek_result_validate_rice_down/rice_down/250831/foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_250831.tsv",
    separator="\t"
).join(
    HNscore_human,
    on="hgnc_symbol_id",
    how="left"
).with_columns(
    (pl.col("hgnc_symbol_id").is_in(top_500_genes).alias("is_in_human_top500")),
    (pl.col("hgnc_symbol_id").is_in(bottom_500_genes).alias("is_in_human_bottom500"))
)

foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_250831.write_csv(
    "../Data/20_foldseek_result_validate_rice_down/rice_down/rice_down_supp9_add_human_HNscore/foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_250831_add_human_HNscore.tsv",
    separator="\t"
)

display(foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_250831)

shape: (7_103, 58)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5  ┆ UniProt    ┆ … ┆ human all  ┆ human     ┆ is_in_hum ┆ is_in_hum │
│ ---        ┆ ---        ┆ ---  ┆ Accession  ┆   ┆ pair       ┆ HN-score  ┆ an_top500 ┆ an_bottom │
│ str        ┆ str        ┆ i64  ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ 500       │
│            ┆            ┆      ┆ str        ┆   ┆ i64        ┆ i64       ┆ bool      ┆ ---       │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆           ┆ bool      │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ A0A0P0UZP7 ┆ … ┆ 322        ┆ 3         ┆ false     ┆ false     │
│ it-248     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ A0A0P0UZP7 ┆ … ┆ 322        ┆ 3         ┆ false     ┆ false     │
│ it-248     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ O24220     ┆ … ┆ 322        ┆ 2         ┆ false     ┆ false     │
│ it-135     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ O24220     ┆ … ┆ 322        ┆ 3         ┆ false     ┆ false     │
│ it-155     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ O24220     ┆ … ┆ 322        ┆ 9         ┆ false     ┆ false     │
│ it-226     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ foldseek-h ┆ Os03g03073 ┆ -204 ┆ Q0DSH9     ┆ … ┆ 322        ┆ -23       ┆ false     ┆ true      │
│ it-3912    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g03073 ┆ -204 ┆ Q0DSH9     ┆ … ┆ null       ┆ null      ┆ false     ┆ false     │
│ it-3913    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g03073 ┆ -204 ┆ Q0DSH9     ┆ … ┆ null       ┆ null      ┆ false     ┆ false     │
│ it-3913    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g03073 ┆ -204 ┆ Q0DSH9     ┆ … ┆ null       ┆ null      ┆ false     ┆ false     │
│ it-3913    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os03g03073 ┆ -204 ┆ Q0DSH9     ┆ … ┆ 322        ┆ 0         ┆ false     ┆ false     │
│ it-3915    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [9]:
foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter1_250831 = pl.read_csv(
    "../Data/20_foldseek_result_validate_rice_down/rice_down/250831/foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter1_250831.tsv",
    separator="\t"
).join(
    HNscore_human,
    on="hgnc_symbol_id",
    how="left"
).with_columns(
    (pl.col("hgnc_symbol_id").is_in(top_500_genes).alias("is_in_human_top500")),
    (pl.col("hgnc_symbol_id").is_in(bottom_500_genes).alias("is_in_human_bottom500"))
)

foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter1_250831.write_csv(
    "../Data/20_foldseek_result_validate_rice_down/rice_down/rice_down_supp9_add_human_HNscore/foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter1_250831_add_human_HNscore.tsv",
    separator="\t"
)

display(foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter1_250831)

shape: (1_698, 58)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5  ┆ UniProt    ┆ … ┆ human all  ┆ human     ┆ is_in_hum ┆ is_in_hum │
│ ---        ┆ ---        ┆ ---  ┆ Accession  ┆   ┆ pair       ┆ HN-score  ┆ an_top500 ┆ an_bottom │
│ str        ┆ str        ┆ i64  ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ 500       │
│            ┆            ┆      ┆ str        ┆   ┆ i64        ┆ i64       ┆ bool      ┆ ---       │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆           ┆ bool      │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ O24220     ┆ … ┆ 322        ┆ 16        ┆ false     ┆ false     │
│ it-244     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ O24220     ┆ … ┆ 322        ┆ 16        ┆ false     ┆ false     │
│ it-244     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ Q9FU17     ┆ … ┆ 322        ┆ -3        ┆ false     ┆ false     │
│ it-240     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ Q9FU17     ┆ … ┆ 322        ┆ 13        ┆ false     ┆ false     │
│ it-252     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os01g01929 ┆ -40  ┆ Q9FU17     ┆ … ┆ 322        ┆ 13        ┆ false     ┆ false     │
│ it-252     ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ foldseek-h ┆ Os07g02584 ┆ -171 ┆ A0A0P0X4D2 ┆ … ┆ 322        ┆ 9         ┆ false     ┆ false     │
│ it-8004    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os07g02584 ┆ -171 ┆ A0A0P0X4D2 ┆ … ┆ 322        ┆ 9         ┆ false     ┆ false     │
│ it-8004    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os07g02584 ┆ -171 ┆ A0A0P0X4D2 ┆ … ┆ 322        ┆ 9         ┆ false     ┆ false     │
│ it-8004    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os07g02584 ┆ -171 ┆ A0A0P0X4D2 ┆ … ┆ 322        ┆ 9         ┆ false     ┆ false     │
│ it-8004    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os07g02584 ┆ -171 ┆ Q0D7E4     ┆ … ┆ 322        ┆ 9         ┆ false     ┆ false     │
│ it-7916    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [17]:
foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter4_250831 = pl.read_csv(
    "../Data/20_foldseek_result_validate_rice_down/rice_down/250831/foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter4_250831.tsv",
    separator="\t"
).join(
    HNscore_human,
    on="hgnc_symbol_id",
    how="left"
).with_columns(
    (pl.col("hgnc_symbol_id").is_in(top_500_genes).alias("is_in_human_top500")),
    (pl.col("hgnc_symbol_id").is_in(bottom_500_genes).alias("is_in_human_bottom500"))
)

foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter4_250831.write_csv(
    "../Data/20_foldseek_result_validate_rice_down/rice_down/rice_down_supp9_add_human_HNscore/foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter4_250831_add_human_HNscore.tsv",
    separator="\t"
)

print(foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter4_250831.select("hit label").unique())
display(foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter4_250831)

shape: (157, 1)
┌────────────────────┐
│ hit label          │
│ ---                │
│ str                │
╞════════════════════╡
│ foldseek-hit-6021  │
│ foldseek-hit-6037  │
│ foldseek-hit-637   │
│ foldseek-hit-4462  │
│ foldseek-hit-5867  │
│ foldseek-hit-2854  │
│ foldseek-hit-5876  │
│ …                  │
│ foldseek-hit-9313  │
│ foldseek-hit-5480  │
│ foldseek-hit-10457 │
│ foldseek-hit-6285  │
│ foldseek-hit-4507  │
│ foldseek-hit-7593  │
│ foldseek-hit-6005  │
└────────────────────┘

shape: (298, 61)
┌────────────┬────────────┬──────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5  ┆ UniProt    ┆ … ┆ human all  ┆ human     ┆ is_in_hum ┆ is_in_hum │
│ ---        ┆ ---        ┆ ---  ┆ Accession  ┆   ┆ pair       ┆ HN-score  ┆ an_top500 ┆ an_bottom │
│ str        ┆ str        ┆ i64  ┆ ---        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ 500       │
│            ┆            ┆      ┆ str        ┆   ┆ i64        ┆ i64       ┆ bool      ┆ ---       │
│            ┆            ┆      ┆            ┆   ┆            ┆           ┆           ┆ bool      │
╞════════════╪════════════╪══════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os09g05542 ┆ -40  ┆ A0A0P0XRD9 ┆ … ┆ 322        ┆ 8         ┆ false     ┆ false     │
│ it-10457   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os09g05542 ┆ -40  ┆ A0A0P0XRD9 ┆ … ┆ 322        ┆ 8         ┆ false     ┆ false     │
│ it-10459   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os09g05542 ┆ -40  ┆ A0A0P0XRD9 ┆ … ┆ 322        ┆ 5         ┆ false     ┆ false     │
│ it-10461   ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os02g05847 ┆ -41  ┆ Q6YY34     ┆ … ┆ 322        ┆ 6         ┆ false     ┆ false     │
│ it-3509    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os02g05847 ┆ -41  ┆ Q6YY34     ┆ … ┆ 322        ┆ 10        ┆ false     ┆ false     │
│ it-3513    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os02g05847 ┆ -41  ┆ Q6YY34     ┆ … ┆ 322        ┆ 10        ┆ false     ┆ false     │
│ it-3513    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os02g05847 ┆ -41  ┆ Q6YY34     ┆ … ┆ 322        ┆ 10        ┆ false     ┆ false     │
│ it-3513    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ …          ┆ …          ┆ …    ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ foldseek-h ┆ Os01g06555 ┆ -107 ┆ Q5SN79     ┆ … ┆ 322        ┆ 1         ┆ false     ┆ false     │
│ it-1712    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g03817 ┆ -119 ┆ A0A0N7KIY3 ┆ … ┆ 322        ┆ 0         ┆ false     ┆ false     │
│ it-5468    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g03817 ┆ -119 ┆ A0A0N7KIY3 ┆ … ┆ 322        ┆ 11        ┆ false     ┆ false     │
│ it-5470    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g05786 ┆ -147 ┆ A0A0P0WE87 ┆ … ┆ 322        ┆ 0         ┆ false     ┆ false     │
│ it-5876    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g05786 ┆ -147 ┆ A0A0P0WE87 ┆ … ┆ 322        ┆ 1         ┆ false     ┆ false     │
│ it-5877    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g05786 ┆ -147 ┆ A0A0P0WE87 ┆ … ┆ 322        ┆ 1         ┆ false     ┆ false     │
│ it-5877    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
│ foldseek-h ┆ Os04g05786 ┆ -147 ┆ A0A0P0WE87 ┆ … ┆ 322        ┆ 1         ┆ false     ┆ false     │
│ it-5878    ┆ 00         ┆      ┆            ┆   ┆            ┆           ┆           ┆           │
└────────────┴────────────┴──────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [19]:
rice_down_human_down = foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter4_250831.filter(
    pl.col("is_in_human_bottom500") == True
)

rice_down_human_down.write_csv(
    "../Data/20_foldseek_result_validate_rice_down/rice_down/rice_down_supp9_add_human_HNscore/foldseek_result_rice_down_domain_panhomology_info_filtercondtion3_filter4_250831_add_human_HNscore_bottom500.tsv",
    separator="\t"
)

print(rice_down_human_down.select("hit label").unique())
pl.Config.set_tbl_rows(14)
display(rice_down_human_down)

shape: (1, 1)
┌───────────────────┐
│ hit label         │
│ ---               │
│ str               │
╞═══════════════════╡
│ foldseek-hit-8311 │
└───────────────────┘

shape: (1, 61)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ hit label  ┆ From       ┆ HN5 ┆ UniProt    ┆ … ┆ human all  ┆ human      ┆ is_in_hum ┆ is_in_hum │
│ ---        ┆ ---        ┆ --- ┆ Accession  ┆   ┆ pair       ┆ HN-score   ┆ an_top500 ┆ an_bottom │
│ str        ┆ str        ┆ i64 ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ 500       │
│            ┆            ┆     ┆ str        ┆   ┆ i64        ┆ i64        ┆ bool      ┆ ---       │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆           ┆ bool      │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ foldseek-h ┆ Os07g05618 ┆ -56 ┆ A0A0P0X7B4 ┆ … ┆ 322        ┆ -12        ┆ false     ┆ true      │
│ it-8311    ┆ 00         ┆     ┆            ┆   ┆            ┆            ┆           ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘